openapi: 3.0.0
info:
  title: Retrieve Books Endpoint
  version: 1.0.0
  description: Retrieve all books available in the library. The description of the endpoint is kept under 500 characters to meet the requirements.

servers:
  - url: https://api.library.com

paths:
  /books:
    get:
      summary: Retrieve a list of all books (up to 500 characters for summary)
      description: Retrieve all books available in the library. The description is kept under 150 characters.
      parameters:
        - name: category
          in: query
          description: Filter books by category (max 150 characters)
          required: false
          schema:
            type: string
        - name: author
          in: query
          description: Filter books by author (max 150 characters)
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: Unique identifier for the book (max 150 characters)
                    title:
                      type: string
                      description: Title of the book (max 150 characters)
                    author:
                      type: string
                      description: Author of the book (max 150 characters)
                    category:
                      type: string
                      description: Category of the book (max 150 characters)
                    publishedDate:
                      type: string
                      description: Publication date in YYYY-MM-DD format (max 150 characters)
                      format: date
                    available:
                      type: boolean
                      description: Availability status (max 150 characters)
                      default: true
